describe('Parser class', () => {
  require('./item.spec')
  require('./map.spec')
  require('./pure.spec')
  require('./ap.spec')
  require('./lazy.spec')
  require('./function.spec')
  require('./flatMap.spec')
  require('./empty.spec')
  require('./option.spec')
  require('./sat.spec')
  require('./string.spec')
})
