describe('methods', () => {
  require('./item.spec')
  require('./map.spec')
  require('./pure.spec')
  require('./ap.spec')
  require('./flatMap.spec')
  require('./empty.spec')
  require('./option.spec')
  require('./sat.spec')
  require('./string.spec')
  require('./many.some.spec')
})
